/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArbitrageRouteImport } from './routes/arbitrage'
import { Route as AuthTestRouteImport } from './routes/auth-test'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DcaRouteImport } from './routes/dca'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as VaultRouteImport } from './routes/vault'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArbitrageRoute = ArbitrageRouteImport.update({
  id: '/arbitrage',
  path: '/arbitrage',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthTestRoute = AuthTestRouteImport.update({
  id: '/auth-test',
  path: '/auth-test',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DcaRoute = DcaRouteImport.update({
  id: '/dca',
  path: '/dca',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arbitrage': typeof ArbitrageRoute
  '/auth-test': typeof AuthTestRoute
  '/dashboard': typeof DashboardRoute
  '/dca': typeof DcaRoute
  '/markets': typeof MarketsRoute
  '/vault': typeof VaultRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arbitrage': typeof ArbitrageRoute
  '/auth-test': typeof AuthTestRoute
  '/dashboard': typeof DashboardRoute
  '/dca': typeof DcaRoute
  '/markets': typeof MarketsRoute
  '/vault': typeof VaultRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arbitrage': typeof ArbitrageRoute
  '/auth-test': typeof AuthTestRoute
  '/dashboard': typeof DashboardRoute
  '/dca': typeof DcaRoute
  '/markets': typeof MarketsRoute
  '/vault': typeof VaultRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arbitrage'
    | '/auth-test'
    | '/dashboard'
    | '/dca'
    | '/markets'
    | '/vault'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arbitrage'
    | '/auth-test'
    | '/dashboard'
    | '/dca'
    | '/markets'
    | '/vault'
  id:
    | '__root__'
    | '/'
    | '/arbitrage'
    | '/auth-test'
    | '/dashboard'
    | '/dca'
    | '/markets'
    | '/vault'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArbitrageRoute: typeof ArbitrageRoute
  AuthTestRoute: typeof AuthTestRoute
  DashboardRoute: typeof DashboardRoute
  DcaRoute: typeof DcaRoute
  MarketsRoute: typeof MarketsRoute
  VaultRoute: typeof VaultRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arbitrage': {
      id: '/arbitrage'
      path: '/arbitrage'
      fullPath: '/arbitrage'
      preLoaderRoute: typeof ArbitrageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-test': {
      id: '/auth-test'
      path: '/auth-test'
      fullPath: '/auth-test'
      preLoaderRoute: typeof AuthTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dca': {
      id: '/dca'
      path: '/dca'
      fullPath: '/dca'
      preLoaderRoute: typeof DcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArbitrageRoute: ArbitrageRoute,
  AuthTestRoute: AuthTestRoute,
  DashboardRoute: DashboardRoute,
  DcaRoute: DcaRoute,
  MarketsRoute: MarketsRoute,
  VaultRoute: VaultRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
